option(DOPE_USE_ALL_LOCAL_PACKAGE_SOURCES "Use all local package sources" OFF)
set(DOPE_LOCAL_PACKAGE_SOURCES_ROOT "" CACHE PATH "Local package sources root")

function (dope_find_local_package_source root name)
	if (DOPE_${name}_LOCAL_SOURCE)
		set(expected_cmake_lists ${root}/${name}/CMakeLists.txt)
		if (EXISTS ${expected_cmake_lists})
			set(DOPE_${name}_LOCAL_SOURCE ${root}/${name} PARENT_SCOPE)
		endif()
	endif()
endfunction()

function (dope_setup_development_package name)
	option(DOPE_${name}_USE_LOCAL_PACKAGE_SOURCE "${name}: Use local package source" OFF)
	foreach (target IN LISTS ${ARGN})
		if (TARGET ${target})
			message(STATUS "Target ${target} already exists, skipping ${name} setup")
			return()
		endif()
	endforeach()
	if (${DOPE_USE_ALL_LOCAL_PACKAGE_SOURCES} OR ${DOPE_${name}_USE_LOCAL_PACKAGE_SOURCE})
		dope_find_local_package_source(${DOPE_LOCAL_PACKAGE_SOURCES_ROOT} ${name})
		if (DOPE_${name}_LOCAL_SOURCE)
			add_subdirectory(${DOPE_${name}_LOCAL_SOURCE} ${name})
			foreach (target IN LISTS ${ARGN})
				if (NOT TARGET ${target})
					message(FATAL_ERROR "Target ${target} does not exist after adding subdirectory ${DOPE_${name}_LOCAL_SOURCE}")
				endif()
			endforeach()
			return()
		endif()
	endif()
	find_package(${name} REQUIRED)
	foreach (target IN LISTS ${ARGN})
		if (NOT TARGET ${target})
			message(FATAL_ERROR "Target ${target} does not exist after find_package(${name})")
		endif()
	endforeach()
endfunction()
